GET http://localhost:3000/food HTTP/1.1

###################################################

GET http://localhost:3000/pages/foodSite/4 HTTP/1.1

###################################################

GET http://localhost:3000/food/45 HTTP/1.1

###################################################

POST http://localhost:3000/food HTTP/1.1
Content-Type: application/json

{
    "number": "7",
    "name": "Sandwich",
    "ingredients": "Pizza-Bread;Tomato-Sauce;Salami;Cheese"
}

###################################################

POST http://localhost:3000/orderentries HTTP/1.1
Content-Type: application/json

{
  "odID": "1",
  "customerID": "1",
  "mealID": "3"
}

###################################################

PUT http://localhost:3000/food/0 HTTP/1.1
Content-Type: application/json

{
  "number": "15",
  "name": "Pizza",
  "ingredients": "Bread;Tomato;Beef;Cheese"
}

###################################################

PUT http://localhost:3000/orderentries/1 HTTP/1.1
Content-Type: application/json

{
  "odID": "1",
  "customerID": "1",
  "mealID": "45"
}

###################################################

POST http://localhost:3000/users/Login HTTP/1.1
Content-Type: application/json

{
  "username": "teacher",
  "password": "teacher"
}
#########################

POST http://localhost:3000/customers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Hentry",
  "lastName": "Saigh",
  "className": "5BHG"
}
#########################

DELETE http://localhost:3000/food HTTP/1.1

###################################################

DELETE http://localhost:3000/orderentries HTTP/1.1

###################################################

DELETE http://localhost:3000/customers/0 HTTP/1.1

###################################################


GET http://localhost:3000/orderdays HTTP/1.1

###################################################
POST http://localhost:3000/orderdays HTTP/1.1
Content-Type: application/json

{  
  "orderdate": "1.1.2023",
  "deadline": "11:00:00"
}

###################################################
