GET http://localhost:3000/food HTTP/1.1

###################################################

GET http://localhost:3000/api/tasks/0 HTTP/1.1

###################################################

POST http://localhost:3000/food HTTP/1.1
Content-Type: application/json

{
    "number": "1",
    "name": "Lasagna",
    "ingredients": "Pizza-Bread;Tomato-Sauce;Salami;Cheese"
}

###################################################

PUT http://localhost:3000/food/0 HTTP/1.1
Content-Type: application/json

{
  "number": "15",
  "name": "Pizza",
  "ingredients": "Bread;Tomato;Beef;Cheese"
}

###################################################

DELETE http://localhost:3000/food HTTP/1.1

###################################################

DELETE http://localhost:3000/food/1 HTTP/1.1

###################################################